import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
    stages: [
        { duration: '30s', target: 80 }, // Ramp up to 20 users
        { duration: '1m', target: 80 },  // Stay at 20 users
        { duration: '30s', target: 0 },  // Ramp down to 0
    ],
};

// Use app:8080 as default for Docker networking, or fallback to localhost if needed via Env
const BASE_URL = __ENV.BASE_URL || 'http://app:8080/api/item';

export default function () {
    // 1. Get Random Item (List from DB)
    let res = http.get(`${BASE_URL}/random`);
    check(res, { 'status was 200': (r) => r.status == 200 });

    // 2. Get Specific Item (Cache-Aside Pattern)
    // We have at least 1-10 IDs from init.sql and new creations
    const id = Math.floor(Math.random() * 10) + 1;
    let itemRes = http.get(`${BASE_URL}/${id}`);
    check(itemRes, { 'item status was 200': (r) => r.status == 200 });

    // 2. Create Item (Write)
    // Run this less frequently (approx 10% of iterations)
    if (Math.random() < 0.1) {
        const payload = JSON.stringify({
            name: `Load Test Item ${__VU}-${__ITER}`,
            description: 'Auto-generated by k6',
            price: Math.floor(Math.random() * 100),
        });

        const params = {
            headers: {
                'Content-Type': 'application/json',
            },
        };

        let writeRes = http.post(`${BASE_URL}/create`, payload, params);
        check(writeRes, { 'status was 201': (r) => r.status == 201 });
    }

    sleep(1);
}
